apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  labels:
    app: flask-app
spec:
  replicas: 2  # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app-container
        image: anuraggg/flask-app:48
        ports:
        - containerPort: 8000  # Flask app port
        - containerPort: 8001  # Prometheus metrics port
        env:
        - name: FLASK_APP
          value: "app.py"

---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  labels:
    app: flask-app
spec:
  type: NodePort  # or LoadBalancer if you need an external IP for the service
  ports:
    - name: http  # Add a unique name for this port
      port: 80  # The port the service will expose (HTTP)
      targetPort: 8000  # The port your Flask app is listening on
      nodePort: 30235  # Optional: manually specify the NodePort
    - name: metrics  # Add a unique name for this port (for Prometheus)
      port: 8001  # Prometheus metrics port
      targetPort: 8001  # The port the Prometheus metrics are exposed on
  selector:
    app: flask-app

