apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  labels:
    app: flask-app
spec:
  replicas: 2  # Adjust replicas as needed
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app-container
        image: anuraggg/flask-app:48
        ports:
        - containerPort: 8000  # Flask app port
        - containerPort: 8001  # Prometheus metrics port (dynamic)
        env:
        - name: FLASK_APP
          value: "app.py"
        - name: PROMETHEUS_PORT
          valueFrom:
            fieldRef:
              fieldPath: metadata.name  # Reference the pod name
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8000
    - name: metrics
      port: 8001
      targetPort: 8001
  selector:
    app: flask-app
